/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AdvancedFeatures_Charpter12_NativeTest */

#ifndef _Included_AdvancedFeatures_Charpter12_NativeTest
#define _Included_AdvancedFeatures_Charpter12_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AdvancedFeatures_Charpter12_NativeTest
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AdvancedFeatures_Charpter12_NativeTest_greeting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
